### ISSUE TITLE
How we should name our files?

### ISSUE THREAD

**Issue by naoki-cpp** [naoki-cpp/Shiketai#3]
ファイルの命名規則をどうしようかという問題

**Comment by naoki-cpp** [comment]
とりあえず理工以外の学部の席を空けておくためにフォルダの構造を変えてみた(masterでこれやっちゃいけないんだろうけどまだ慣れてなくてミスってしまった許して...ほんとはブランチ作るべきだった)

**Comment by nison-st** [comment]
結局ファイルだけが一人歩きしちゃって何のファイルかわかんないというのは困るので、
学部_科目名_年度_中身.拡張子
でどうだろう
例:
ST_Math2B_2017_Q.pdf

**Comment by nison-st** [comment]
他学部の科目ね
取りあえずは理工の必修と日吉共通でいんじゃないかとおもうけど

**Comment by naoki-cpp** [comment]
なるほど. 中身の記号は
- Q:問題
- A:解答
- N:ノート or レジュメ
でいいかな？ノートやレジュメ等で題名つけたいときは  
学部_科目名_中身_題名.拡張子
でいいかな

**Comment by nison-st** [comment]
学部記号:トップのReadmeに記載
ST:(日吉)理工学部
HC:日吉共通設置科目
以下は設置予定今のところは…
LT:文学部
BC:商学部
LL:法学部法律学科
LP:法学部政治学科
LC:法学部共通
EC:経済学部
PH:薬学部
MD:医学部
科目名記号：学部別フォルダ内で定義
年度：過去問は試験が行われた年度、それ以外はその文書が作成された（であろう）年度
内容：科目別フォルダ内で定義
過去問に関しては
Q:問題
A:解答
QA:両方のセット
くらいでいいんじゃないかな。

**Comment by naoki-cpp** [comment]
今はまだいいけどREADME.mdに書くことが多くなりそうだったらWikiも活用することにしようか.

**Comment by nison-st** [comment]
うーんWikiもありっちゃありだけどREADME.mdに書くのが一番参照しやすいよね（ど素人

**Comment by naoki-cpp** [comment]
そうだね. 入れ子式になってるしいちいちWikiに書くのも煩雑になりそう.

**Comment by naoki-cpp** [comment]
あ、SFC忘れてたわ(大問題

**Comment by naoki-cpp** [comment]
SFCはSFCの科目があったりするのでSFCでまとめてしまおうかと思う。
中間試験の問題はFQ、期末試験の問題はLQとします。解答はそれぞれFA、LAとします。
とりあえずこれでいいかと思うのでcloseします。
